/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.gui.Window;
//import javax.swing.JFrame;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

	Window window = new Window("Testing");
    }
}
